seed: 
	docker-compose exec db psql -U timoheihe  -d postgres  -h localhost -f seeds/seed.sql

seed-production: 
	docker-compose exec db psql -U timoheihe  -d postgres  -h localhost -f seeds/seed-production.sql