name: Backend Testing

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
      - uses: actions/checkout@v1

      - name: Setup NodeJs
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Install Dependencies
        run: cd ./server && yarn install

      - name: Run test
        run: cd ./server && yarn test